export const types = {
  APP_CONFIG: {
    INVERT_THEME: 'INVERT_THEME',
    TOGGLE_DRAWER: 'APP_CONFIG/TOGGLE_DRAWER',
    RESET_RIGHT_DRAWER: 'APP_CONFIG/RESET_RIGHT_DRAWER',
    OPEN_RIGHT_DRAWER: 'APP_CONFIG/OPEN_RIGHT_DRAWER',
  },
};
